export { deleteUserAddress } from './address/deleteUserAddress';
export { getUserAddress } from './address/getUserAddress';
export { setUserAddress } from './address/setUserAddress';
export { authenticate, login } from './auth/login';
export { logout } from './auth/logout';
export { registerUser } from './auth/register';
export { getCategories } from './categories/getCategories';
export { getOrderById } from './order/getOrderById';
export { getOrdersByUser } from './order/getOrdersByUser';
export { getPaginatedOrders } from './order/getPaginatedOrders';
export { placeOrder } from './order/placeOrder';
export { paypalCheckPayment } from './payments/paypalCheckPayment';
export { setTransactionId } from './payments/setTransactionId';
export { createUpdateProduct } from './products/createUpdateProduct';
export { deleteProductImage } from './products/deleteProductImage';
export { getProductBySlug } from './products/getProductBySlug';
export { getStockBySlug } from './products/getStockBySlug';
export { getPaginatedProductsWithImages } from './products/product-pagination';
export { changeUserRole } from './users/changeUserRole';
export { getPaginatedUsers } from './users/getPaginatedUsers';

